package Sistema.Gestion.Academica.Vista;

import Sistema.Gestion_Academica.Controlador.Matricula_Controlador;
import Sistema.Gestion_Academica.Entidades.Asignatura;
import Sistema.Gestion_Academica.Entidades.Estudiante;
import Sistema.Gestion_Academica.Entidades.Matricula;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Javier
 */
public class Pnl_Matricula extends javax.swing.JPanel {

    private Matricula_Controlador controlador;

    
    public Pnl_Matricula() {
        initComponents();
        controlador = new Matricula_Controlador(this);
        controlador.cargarCombos();
        controlador.listar();
    }
    
    public Estudiante getEstudiante() {
        return (Estudiante) cboEstudiante.getSelectedItem();
    }
    public Asignatura getAsignatura() {
        return (Asignatura) cboAsignatura.getSelectedItem();
    }
    public String getPeriodo() {
        return txtPeriodo.getText().trim();
    }
    public String getNota() {
        return txtNota.getText().trim();
    }
    public String getEstado() {
        return cboEstado.getSelectedItem().toString();
    }
    public int getFilaSeleccionada() {
        return tblMatriculas.getSelectedRow();
    }

    public void llenarComboEstudiantes(List<Estudiante> lista) {
        DefaultComboBoxModel<Estudiante> modelo = new DefaultComboBoxModel<>();
        for (Estudiante e : lista) {
            modelo.addElement(e);
        }
        cboEstudiante.setModel(modelo);
    }

    public void llenarComboAsignaturas(List<Asignatura> lista) {
        DefaultComboBoxModel<Asignatura> modelo = new DefaultComboBoxModel<>();
        for (Asignatura a : lista) {
            modelo.addElement(a);
        }
        cboAsignatura.setModel(modelo);
    }

    public void mostrarMatriculas(List<Matricula> lista) {
        String[] columnas = {"Estudiante", "Asignatura", "Periodo", "Fecha",
                             "Nota", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };

        for (Matricula m : lista) {
            Object[] fila = {
                m.getEstudiante().getNombres() + " " + m.getEstudiante().getApellidos(),
                m.getAsignatura().getNombre(),
                m.getPeriodo(), m.getFecha(), m.getNota(), m.getEstado()};
            modelo.addRow(fila);
        }
        tblMatriculas.setModel(modelo);
    }

    public void cargarDatos(Matricula m) {
        txtPeriodo.setText(m.getPeriodo());
        txtNota.setText(String.valueOf(m.getNota()));
        cboEstado.setSelectedItem(m.getEstado());

        for (int i = 0; i < cboEstudiante.getItemCount(); i++) {
            if (cboEstudiante.getItemAt(i).getCedula()
                    .equals(m.getEstudiante().getCedula())) {
                cboEstudiante.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < cboAsignatura.getItemCount(); i++) {
            if (cboAsignatura.getItemAt(i).getCodigo()
                    .equals(m.getAsignatura().getCodigo())) {
                cboAsignatura.setSelectedIndex(i);
                break;
            }
        }
    }

    public void limpiarCampos() {
        txtPeriodo.setText("");
        txtNota.setText("0");
        cboEstado.setSelectedIndex(0);
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error",
                                      JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
