package Sistema.Gestion.Academica.Vista;

import Sistema.Gestion_Academica.Controlador.Asignatura_Controlador;
import Sistema.Gestion_Academica.Entidades.Asignatura;
import Sistema.Gestion_Academica.Entidades.Docente;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Javier
 */
public class Pnl_Asignatura extends javax.swing.JPanel {

    private Asignatura_Controlador controlador;
    
    public Pnl_Asignatura() {
        initComponents();
        controlador = new Asignatura_Controlador(this);
        controlador.cargarDocentes();
        controlador.listar();
    }
    
     public String getCodigo() {
        return txtCodigo.getText().trim().toUpperCase();
    }
    public String getNombre() {
        return txtNombre.getText().trim();
    }
    public int getCreditos() {
        return Integer.parseInt(cboCreditos.getSelectedItem().toString());
    }
    public Docente getDocente() {
        return (Docente) cboDocente.getSelectedItem();
    }
    public int getFilaSeleccionada() {
        return tblAsignaturas.getSelectedRow();
    }

    public void llenarComboDocentes(List<Docente> docentes) {
        DefaultComboBoxModel<Docente> modelo = new DefaultComboBoxModel<>();
        for (Docente d : docentes) {
            modelo.addElement(d);
        }
        cboDocente.setModel(modelo);
    }

    public void mostrarAsignaturas(List<Asignatura> lista) {
        String[] columnas = {"Codigo", "Nombre", "Creditos", "Docente"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };

        for (Asignatura a : lista) {
            String nombreDocente = "Sin asignar";
            if (a.getDocente() != null) {
                nombreDocente = a.getDocente().getNombres() + " "
                              + a.getDocente().getApellidos();
            }
            Object[] fila = {a.getCodigo(), a.getNombre(), a.getCreditos(),
                             nombreDocente};
            modelo.addRow(fila);
        }
        tblAsignaturas.setModel(modelo);
    }

    public void cargarDatos(Asignatura a) {
        txtCodigo.setText(a.getCodigo());
        txtNombre.setText(a.getNombre());
        cboCreditos.setSelectedItem(String.valueOf(a.getCreditos()));

        // Busca el docente en el combo comparando la cédula
        if (a.getDocente() != null) {
            for (int i = 0; i < cboDocente.getItemCount(); i++) {
                Docente d = cboDocente.getItemAt(i);
                if (d.getCedula().equals(a.getDocente().getCedula())) {
                    cboDocente.setSelectedIndex(i);
                    break;
                }
            }
        }
    }

    public String getCodigoDeTabla(int fila) {
        return tblAsignaturas.getValueAt(fila, 0).toString();
    }

    public void limpiarCampos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtCodigo.requestFocus();
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error",
                                      JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
