package Sistema.Gestion.Academica.Vista;

import Sistema.Gestion_Academica.Controlador.Reporte_Controlador;
import Sistema.Gestion_Academica.Entidades.Asignatura;
import Sistema.Gestion_Academica.Entidades.Docente;
import Sistema.Gestion_Academica.Entidades.Estudiante;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * @author Javier
 */
public class Pnl_Reporte extends javax.swing.JPanel {

    private Reporte_Controlador controlador;
    
    public Pnl_Reporte() {
        initComponents();
        controlador = new Reporte_Controlador(this);
        controlador.cargarCombos();
    }
    
     public Estudiante getEstudiante() {
        return (Estudiante) cboEstudiante.getSelectedItem();
    }
    public Asignatura getAsignatura() {
        return (Asignatura) cboAsignatura.getSelectedItem();
    }
    public Docente getDocente() {
        return (Docente) cboDocente.getSelectedItem();
    }

    public void llenarComboEstudiantes(List<Estudiante> lista) {
        DefaultComboBoxModel<Estudiante> modelo = new DefaultComboBoxModel<>();
        for (Estudiante e : lista) {
            modelo.addElement(e);
        }
        cboEstudiante.setModel(modelo);
    }

    public void llenarComboAsignaturas(List<Asignatura> lista) {
        DefaultComboBoxModel<Asignatura> modelo = new DefaultComboBoxModel<>();
        for (Asignatura a : lista) {
            modelo.addElement(a);
        }
        cboAsignatura.setModel(modelo);
    }

    public void llenarComboDocentes(List<Docente> lista) {
        DefaultComboBoxModel<Docente> modelo = new DefaultComboBoxModel<>();
        for (Docente d : lista) {
            modelo.addElement(d);
        }
        cboDocente.setModel(modelo);
    }

    public void recargar() {
        controlador.cargarCombos();
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error",
                                      JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboEstudiante = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboAsignatura = new javax.swing.JComboBox<>();
        cboDocente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEstudiantes = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnAsignaturas = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jLabel1.setText("Estudiante");

        jLabel2.setText("Historial Academico");

        jLabel3.setText("Asignatura");

        jLabel4.setText("Docente");

        jLabel5.setText("Estudiantes por Asignatura");

        jLabel6.setText("Asignaturas por Docente");

        btnEstudiantes.setText("Imprimir");
        btnEstudiantes.addActionListener(this::btnEstudiantesActionPerformed);

        btnHistorial.setText("Imprimir");
        btnHistorial.addActionListener(this::btnHistorialActionPerformed);

        btnAsignaturas.setText("Imprimir");
        btnAsignaturas.addActionListener(this::btnAsignaturasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboEstudiante, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboAsignatura, javax.swing.GroupLayout.Alignment.LEADING, 0, 190, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnHistorial))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnAsignaturas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnEstudiantes)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnHistorial))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnEstudiantes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnAsignaturas))
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
    controlador.generarEstudiantesPorAsignatura();
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
    controlador.generarHistorial();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignaturasActionPerformed
    controlador.generarAsignaturasPorDocente();
    }//GEN-LAST:event_btnAsignaturasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignaturas;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JComboBox<Asignatura> cboAsignatura;
    private javax.swing.JComboBox<Docente> cboDocente;
    private javax.swing.JComboBox<Estudiante> cboEstudiante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
